@startuml Skyjo
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

class Skyjo{
    main(args : String[*])
}

class Carte{
    - valeur : Integer
    + Carte(valeur : Integer)
    + getValeur() : Integer
    + setValeur(valeur : Integer)

}

class Joueur{
    - nom : String
    + Joueur()
    + Joueur(nom : String)
    + getNom() : String
    + setNom(nom : String)
    + piocher() : Carte
}

class GrilleJoueur{
    - sommePoints : Integer
    + getColonne() : Carte[*]
    + retirerColonne()
    + addObserver(obs : GrilleObserver)
    + notifyObservers()
}

Joueur "1\n - grille" o--> GrilleJoueur

interface GrilleObserver{
    + Update()
}
GrilleJoueur "*\n- observers" o-u-> GrilleObserver
class Partie{
    - nbJoueurs : Integer
    + distribuer()
    + getNbJoueurs()
}

Partie "*\n- pioche" o--> Carte
Partie "*\n- defausse" o--> Carte
GrilleJoueur "*\n - grille" o-r-> Carte

@enduml